### ISSUE TITLE
Improve mechanism for linking/referencing files

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-repository_owncloud#15]
Right now, a reference is created by generating a public share via ownCloud's OCS API, and redirecting to that link in future requests. That means that anyone who guesses the link can access the file, even though he/she does not have access to the corresponding course.

This works – for now – but can be improved. Have a look at Moodle 3.3's [Google Docs](https://github.com/moodle/moodle/tree/MOODLE_33_STABLE/repository/googledocs) / [OneDrive](https://github.com/moodle/moodle/tree/MOODLE_33_STABLE/repository/onedrive) repositories for a better way.

This should be done without breaking existing links. Automated transition would be A+, but it suffices if existing links just keep working the way they are.

**Comment by Dagefoerde** [comment]
Key function: for future reference: `https://github.com/moodle/moodle/blob/6aaea768a16000310039e64dcbef726e69aa703d/repository/googledocs/lib.php#L903`

**Comment by Dagefoerde** [comment]
Related to #21

**Comment by NinaHerrmann** [comment]
Further improvements that are not included in the requirements from the pull request are:

- [ ] **Make the method to create a folder path more efficient.** Currently every folder is checked and created separately
- [ ] **Embellish the Login** by now merely a link is displayed
- [ ]  **Delete files consistently** If the deletion of files fails this is ignored. For clarity possible alternative actions should be evaluated
- [ ] **Visualize procedure** This would increase the comprehension of different processes and make it easier to introduce the plugin to other people (and to consider all possible reasons for exceptions).
- [x] **Set custom folder name** Writhe a setting where a custom name for the folder can be determined by the admin/course administrator
- [ ] **Enable different permission rights** E.g. enable user to merely read, to writhe or the share the file with other users.

**Comment by Dagefoerde** [comment]
The mechanism for linking/referencing files has been greatly improved by adding access controlled links (in the upcoming release). If you feel any of the other improvements are necessary, please create separate issues.
