### ISSUE TITLE
Oauth not found in marketplace

### ISSUE THREAD

**Issue by hermannkm** [learnweb/moodle-repository_owncloud#19]
I am using owncloud 10.0 on ubuntu 16.04 with owncloud standard edition. Should this configuration work?
Oauth app is not shown in my marketplace.
 
Do I have to manually install the Oauth app (e.g. from https://github.com/owncloud/oauth2) or should this be available with standard (not enterprise) edition?

**Comment by hermannkm** [comment]
Sorry - found everything needed in additional documentation.

**Comment by Dagefoerde** [comment]
Hi @hermannkm, thanks for reporting back! Glad to hear that it is solved.
