### ISSUE TITLE
"error/Could not upgrade oauth token" when connecting Nextcloud 12

### ISSUE THREAD

**Issue by fishfree** [learnweb/moodle-repository_owncloud#20]
I followed [the documentation](https://github.com/learnweb/moodle-repository_owncloud/blob/master/README.md). After I click on "Grant access" on the pop-up Nextcloud window, the pop-up window redirect to Moodle page with this error info.

**Comment by fishfree** [comment]
I logout from Nextcloud, then retry, problem disappeared.

**Comment by Dagefoerde** [comment]
Hi, great to hear that you solved it! Thanks for reporting back.
