### ISSUE TITLE
Authentifizierter Nutzer darf kein Repository hinzufügen.

### ISSUE THREAD

**Issue by andreasschenkel** [learnweb/moodle-repository_owncloud#22]
Wenn man als normaler User in den Eingenen Dateien versucht ein Oqncloud-Repository hinzuzufügen erhält man die Meldung: "Sie besitzen derzeit keine Rechte, dies zu tun (ownCloud-Konfiguration). "
Ein Admin kann Repo hinzufügen.
moodle 3.3.2+

**Comment by Dagefoerde** [comment]
Hallo Andreas, das ist so gewollt: Wenn eine Instanz hinzugefügt wird, muss ein Issuer ausgewählt werden. Issuers können aber nur von Administratoren angelegt werden. Daher können Nutzer keine sinnvolle Auswahl treffen, die nicht bereits von Administratoren vorgegeben worden wäre.
Zur Anmeldung mit eigenen Nutzerdaten muss aber keine private Instanz angelegt werden; jeder meldet sich immer im privaten Bereich an.
