### ISSUE TITLE
set up everything according to installation instructions, but unable to connect to onecloud

### ISSUE THREAD

**Issue by stemiwe** [learnweb/moodle-repository_owncloud#24]
we have a nextcloud12 set up at our site, and I tried to connect it to moodle using your repository plugin.

I configured everything according to the instructions, when I try to access the repository from the moodle file picker, I first get a "login to your account" button

Once i click the button, a new popup window opens that asks me to grant access to Moodle. After logging in, I get the following error:

**error/Could not upgrade oauth token

×Debug info: 
Error code: Could not upgrade oauth token
$a contents:
×Stack trace:
line 555 of /lib/oauthlib.php: moodle_exception thrown
line 469 of /lib/oauthlib.php: call to oauth2_client->upgrade_token()
line 386 of /repository/owncloud/lib.php: call to oauth2_client->is_logged_in()
line 62 of /repository/repository_callback.php: call to repository_owncloud->callback()**

any help would be appreciated

**Comment by Dagefoerde** [comment]
On which version of Moodle are you currently, especially which build date?

**Comment by stemiwe** [comment]
Moodle 3.3.1+ (Build: 20170714)

**Comment by stemiwe** [comment]
thats the error msg we get on the cloud side:

{"reqId":"5pSkDcWGoMi7JZqO6iJ5","level":3,"time":"2017-10-05T13:31:12+00:00","remoteAddr":"10.6.16.30","user":"--","app":"index","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"Exception: {\"Exception\":\"OCA\\\\OAuth2\\\\Exceptions\\\\AccessTokenNotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/oauth2\\\/lib\\\/Controller\\\/OauthApiController.php(71): OCA\\\\OAuth2\\\\Db\\\\AccessTokenMapper->getByCode('WVZqT0O7oZYINNR...')\\n#1 [internal function]: OCA\\\\OAuth2\\\\Controller\\\\OauthApiController->getToken(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OAuth2\\\\Controller\\\\OauthApiController), 'getToken')\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OAuth2\\\\Controller\\\\OauthApiController), 'getToken')\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\OAuth2\\\\\\\\Cont...', 'getToken', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/oauth2\\\/ap...')\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/oauth2\\\/lib\\\/Db\\\/AccessTokenMapper.php\",\"Line\":53}","userAgent":"MoodleBot\/1.0","version":"12.0.3.3"}
root@cloud12:/var/www/html/nextcloud/core/skeleton# date
Thu Oct  5 15:38:37 CEST 2017

**Comment by Dagefoerde** [comment]
Sorry, in that case you are experiencing a Moodle bug that is fixed since Build 20170817. Until then, tokens that contain a + (plus) sign were interpreted wrong. Exactly those tokens are issued by Nextcloud.

So the solution is to upgrade Moodle, sorry for that. Using a recent 3.3.1+/3.3.2 stable will be sufficient!

**Comment by stemiwe** [comment]
thanks for the input, we will update next week in that case :)
