### ISSUE TITLE
set up everything according to installation instructions, no error messages, but no files are displayed

### ISSUE THREAD

**Issue by stemiwe** [learnweb/moodle-repository_owncloud#26]
so, in the meantime we upgraded to the latest Moodle build, so in theory everything should work now. When I login directly into my owncloud account, I can see my files just fine.

But when I try to access them from Moodle, it tells me "No files available"

Here is what happens exactly:

- I select our ownCloud instance in the Moodle file picker
- I click on "Log in to your account"
- A popup window opens and asks me to grant access to my account
- I enter my username and password for owncloud
- The popup window closes, Moodle tells me "No files available"

Could it be an issue that our test site does not use https? Or might something else be configured incorrectly?

**Comment by Dagefoerde** [comment]
Yes, that is possible. Another reason could be that your Moodle server cannot reach the ownCloud server for some reason. 

The authentication with username and password happens in the browser, so the end-user has to reach the ownCloud server. After that, for file listing and uploading, the servers have to communicate with each other, i.e. the Moodle server does everything on behalf of the user, but on its own. 

So it's worth assuring that IP routes are set up correctly. This can be tedious e.g. if everything is in Docker containers, because then `localhost` always means something different...

**Comment by ndunand** [comment]
@Dagefoerde +1 here same problem

Installation went fine, user popup auth looks alright, but then "no files". To make sure, both sites are HTTPS.

IP routes look alright, as I can SSH from moodle-server to owncloud-server and back.

Here's what I have on the OwnCloud server Apache logs : 
`[10/Nov/2017:14:05:16 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 4607 "-" "Moodle WebDav Client (3.3 oauth polyfill)`

**Comment by ndunand** [comment]
@Dagefoerde from the README of this plugin:

> It makes use of a slightly modified version of Moodle's webdav_client (lib/webdavlib.php) that was extended to incorporate OAuth-2-authenticated requests.

It looks like requests are not (properly) authenticated. How can I check that it is indeed the modifier WebDAV client that's being used by this plugin?

**Comment by Dagefoerde** [comment]
@ndunand thanks for the assessmetn. "Moodle WebDav Client (3.3 oauth polyfill)" verifies that this is using the modified WebDAV client. I will look into it and get back to you.

**Comment by Dagefoerde** [comment]
So I tested this with a fresh reinstall of Moodle 3.3 and this plugin in v3.4-r2 again and can confirm that things work as they should, i.e. I can see the files.

Your line `"PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1"` indicates that the token exchange has worked, which is great. It might also indicate that a few Apache modules are missing/misconfigured at the ownCloud Apache server (resulting in dropped authorization headers). Please have a look at this issue: https://github.com/owncloud/oauth2/issues/49 maybe the modules that are described there can help.

**Comment by Dagefoerde** [comment]
Particularly the following excerpt:
> but two modules have been missing on the server: headers and rewrite [...]
> Installing these modules proved to make the login from the clients work seamlessly.

**Comment by ndunand** [comment]
@Dagefoerde thanks for looking into this.

I've checked and those 2 Apache modules were already enabled, but then I thought of the `.htaccess` file, as some of the auth seems to be worked out there. I suspected that some of these directives were not enforced, thus set an extra

```
<Directory /var/www/owncloud/>
    AllowOverride All
</Directory>
```

in the OwnCloud Apache server configuration, and ... voilà !

All now works as expected. I should have seen this from the Apache logs, but anyway thanks !

**Comment by Dagefoerde** [comment]
@ndunand Thanks for getting back to me.  I am glad that this is resolved for you. I will close this issue as the original description was identical. @webers-technikum-wien please check if this works for you as well; otherwise please reopen this issue with additional information.
Thank you all!
