### ISSUE TITLE
When using File Picker, Login into Nextcloud shows up nextcloud webpage instead of files in nextcloud

### ISSUE THREAD

**Issue by pkmkrishnakumar-zz** [learnweb/moodle-repository_owncloud#31]
When using File Picker shows up like this
![image](https://user-images.githubusercontent.com/29704829/37479361-810e4152-28a2-11e8-83a5-611a3a30d92a.png)

When login into the nextcloud via popup window ,it logs into nextcloud and not showing the files in file picker.

![image](https://user-images.githubusercontent.com/29704829/37479448-b2c89bf2-28a2-11e8-9041-d505ddce0623.png)

Thus help me out to set up the nextcloud repository in moodle

**Comment by Dagefoerde** [comment]
Are these screenshots a direct sequence, or do you see any other screens in the meantime? (Like a login form or buttons for authorisations?)

**Comment by pkmkrishnakumar-zz** [comment]
On first attempt a autherization screen displayed in which grant access is provided following that a login screen of nextcloud is being dispalyed , in which i gave the login credentials of the user.

After which it show up the default screen of nextcloud instead of files in nextcloud in file picker window.

Other details: 
Nextcloud Version: 13.0.1
Moodle : 3.4+
Self Signed Certificate for Nextcloud (https://lms-jit/nextcloud)
Moodle is access via http and not https (http://lms-jit/moodle)

**Comment by Dagefoerde** [comment]
Now that you're logged into Nextcloud in your browser already, if you press "Log in to your account" in Moodle again, which screen comes up?

**Comment by pkmkrishnakumar-zz** [comment]
In moodle no response , 
It keep on shows the "Log in to your account"

If click it doesn't shows up, no response

If i close the pop up window opened earlier, and click the "Log in to your account" in moodle again a pop up window shows up as earlier (Logged in window of nextcloud.

Do i make any mistake in configuring in moodle?

I will show the settings made in moodle:

![image](https://user-images.githubusercontent.com/29704829/37551371-65031de8-29c4-11e8-9825-8897bd59e263.png)
![image](https://user-images.githubusercontent.com/29704829/37551377-77837170-29c4-11e8-8497-43ca8d3f3087.png)
![image](https://user-images.githubusercontent.com/29704829/37551379-82b13f96-29c4-11e8-80c1-9319e5c56672.png)
![image](https://user-images.githubusercontent.com/29704829/37551381-90b8c884-29c4-11e8-81d6-416f1319e720.png)

**Comment by Dagefoerde** [comment]
All your Moodle configuration looks good to me. Therefore I think the error is with Nextcloud. Please have a look at your Nextcloud logs while attempting a connection and see if something comes up. Also, please double-check your Apache configuration according to the Nextcloud documentation. If the issue persists, the Nextcloud community might be able to help you out.

**Comment by pkmkrishnakumar-zz** [comment]
Nextcloud setting for OAuth 2.0 Clients

![image](https://user-images.githubusercontent.com/29704829/37650953-88aee70a-2c5c-11e8-947d-8478452a9e4e.png)


Can anyone provide me the minimum configuration requirements of Apache2 and Nextcloud, to make this app work in moodle.
Is there any dependencies in nextcloud or apache to be satisfied?

I am not sure to what to do next? Please any one guide me to sort this problem out.

**Comment by Dagefoerde** [comment]
I'm really just a Moodle plugin developer, so I can't help out here, sorry. I only know about Apache modules that are required for ownCloud, but this might or might not apply to Nextcloud: https://github.com/owncloud/oauth2/issues/110. Probably it's worth a try.

Maybe someone will see your inquiry here and can help, otherwise the Nextcloud community at https://help.nextcloud.com will be able to help you get OAuth 2 working in your Nextcloud+Apache setup.

**Comment by pkmkrishnakumar** [comment]
Interestingly I found some other sequence of results by changing some configs in moodle. Screenshots as in sequence of operations:
![image](https://user-images.githubusercontent.com/29704829/37688086-37a54b98-2cc4-11e8-893c-cdc1bb490875.png)
Next by Clicking on Log in to the Account
![image](https://user-images.githubusercontent.com/29704829/37688119-6b496114-2cc4-11e8-9503-00ebfe76e826.png)
Next Clicking to Grant Access
![image](https://user-images.githubusercontent.com/29704829/37688160-a205cc6a-2cc4-11e8-8577-cff41b29b0f3.png)
Now Pop up Page redirects to Moodle Homepage of the user
![image](https://user-images.githubusercontent.com/29704829/37688206-d4da0b24-2cc4-11e8-8c8a-b85b23be5c01.png)


I am not sure what to do next

In spite I checked with Nextcloud Configuration in Apache comparing with Owncloud both seems similar, all default config is been followed

**Comment by pkmkrishnakumar-zz** [comment]
Interesting I got other kind of results by changing Moodle settings as shown below:
![image](https://user-images.githubusercontent.com/29704829/37688310-66761bb8-2cc5-11e8-88c8-41bc8ec4c6c8.png)

Sequence of Operations in Moodle after making some change in OAuth 2 Services:
![image](https://user-images.githubusercontent.com/29704829/37688331-86aa6eb6-2cc5-11e8-97ae-c6a8b4585d71.png)

Click on Login in to your account

![image](https://user-images.githubusercontent.com/29704829/37688342-98ae54b0-2cc5-11e8-9a0d-4fea845324a1.png)

Click on Grant Access

![image](https://user-images.githubusercontent.com/29704829/37688352-a2618d1a-2cc5-11e8-8d6b-787aa0c29c6f.png)

Log in to your account

Now Pop up window displays default home page of moodle instead of redirecting to contents of cloud in file picker 

![image](https://user-images.githubusercontent.com/29704829/37688665-2be5b3d0-2cc7-11e8-8f6d-9762fa3335d3.png)


Earlier in the post, I have posted previous settings in OAuth 2 Services, with that settings, pop up window did not close, but shows up nextcloud home page
Now with current settings (in this post), pop up window did not close as earlier case, but shows up moodle home page

Its disgusting for me whats happening

Seriously, I am not a coder/programmer either but an novice end user 

Please help me out where is the mistake either in Moodle or Nextcloud

Nextcloud OAuth 2.0 Client settings:
![image](https://user-images.githubusercontent.com/29704829/37688752-9438e0f6-2cc7-11e8-853e-64f6293ab183.png)

Is there any thing to do with redirect url in nextcloud

**Comment by Dagefoerde** [comment]
The redirect URI that you set up in Nextcloud looks good to me. 
I assume that this error results from a Nextcloud misconfiguration, because Nextcloud is redirecting you to a wrong page.
However, as I said, I am at a loss here. Sorry I can't help you any further. Please refer to the links I posted above, especially to the Nextcloud community (https://help.nextcloud.com) because there you will find people who know more about Nextcloud who may even have encountered your particular error. Thanks.
