### ISSUE TITLE
Can only link to files, not to directories

### ISSUE THREAD

**Issue by stemiwe** [learnweb/moodle-repository_owncloud#43]
In the web client of ownCloud, it is possible to link to directories, not just files.

Using the Moodle plugin, I cannot link to directories, since as soon as I click on a directory the directory opens and displays its content.

This severely limits the functionality of the Moodle plugin and should be changed

**Comment by Dagefoerde** [comment]
Thanks for your request. You are right, it would be really nice to have this. However, this is a piece of functionality that the plugin cannot control: The Moodle code prescribes that you can only navigate into a directory for browsing it, but does not offer any other kind of interaction. So the general concept of doing something else with a directory would be a feature request that you could raise at tracker.moodle.org. I would welcome and support the request.

Also, please keep in mind that this plugin will not receive new developments, with the exception of security fixes, as the plugin is now maintained as part of Moodle core (there as `repository_nextcloud`).  Therefore, such a feature would be developed there.
